[profile.default]
src = "src"
out = "out"
libs = ["lib"]


remappings = [
    "@ds-test/=lib/forge-std/lib/ds-test/src/",
    "@forge-std/=lib/forge-std/src/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "@vec-multicaller/=lib/multicaller/src/",
    "@safe-contracts/=lib/safe-contracts/contracts/",
    "@src/=src/",
    "@test/=test/",
    "@script/=script/",
    "@safe-contracts/=lib/safe-contracts/contracts/",


    "@uniswap-v3-periphery/=lib/v3-periphery/contracts/",
    ### @dev These imports are so we can compile the uniswapv3 periphery contracts inside tests
    "@uniswap/v3-core/=lib/v3-periphery/node_modules/@uniswap/v3-core",
    "@openzeppelin/contracts/=lib/v3-periphery/node_modules/@openzeppelin/contracts/",
    #####

    "@uniswap-v3-core/=lib/v3-core/contracts/",
]

fs_permissions = [{ access = "read", path = "./"}]